name: Release Obsidian plugin
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          # List the specific files Obsidian needs
          artifacts: "main.js,manifest.json,styles.css,Readme.MD,LICENSE" 
          token: ${{ secrets.GITHUB_TOKEN }}
